name: Terraform Plan Summarizer Workflow

on:
  workflow_call:
    inputs:
      plan_file:
        description: "Terraform plan file to summarize"
        required: true
        type: string
    secrets:
      mistral_api_key:
        description: "Mistral API key"
        required: true

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Summarize Terraform plan
        run: python -m terrasummary.main ${{ inputs.plan_file }}
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
