name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  summarize:
    needs: generate-tf-plan
    uses: ./.github/workflows/terrasummary.yaml
    with:
      plan_file: tf-plan-out-sample.txt
    secrets:
      mistral_api_key: ${{ secrets.MISTRAL_API_KEY }}
