name: Test Terrasummary Action
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-terrasummary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terrasummary (local branch)
        uses: ./
        with:
          mistral_api_key: ${{ secrets.MISTRAL_API_KEY }}
          plan_file: tfplan.txt
